/*
 * This source file was generated by the Gradle 'init' task
 */
package agh.ics.concurrency;
import java.lang.Thread;

public class App {

    public static void main(String[] args) {
        new ProducerConsumer().runOne();
    }
}
