/*
 * This source file was generated by the Gradle 'init' task
 */
package agh.ics.concurrency;
import agh.ics.concurrency.lab3.Run;

public class App {

    public static void main(String[] args) {
        new Run().run(10, 10, 20);
    }
}
